server:
  port: 8080


spring:
  datasource:
    driver-class-name: com.mysql.cj.jdbc.Driver
    url: jdbc:mysql://localhost:3306/zyg
    username: root
    password: 123456



mybatis:
  type-aliases-package: springboot_maven.pojo #别名
  mapper-locations: classpath:/mybatis/*.xml   #xml文件路径




